name: new_piiink
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+6

environment:
  sdk: ">=3.0.0 <4.0.0"
  # sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.2
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.8.4
  dio: ^5.7.0
  url_launcher: ^6.3.2
  dropdown_button2: ^2.3.9
  # flutter_barcode_scanner:
  #   git:
  #     url: https://github.com/itsAyyazdev/flutter_barcode_scanner.git
  flutter_svg: ^2.0.9
  shared_preferences: ^2.0.15
  outline_gradient_button: ^2.0.0+1
  # intl: ^0.18.0
  location: ^8.0.0
  carousel_slider: ^5.0.0
  flutter_stripe: ^11.4.0
  flutter_html: ^3.0.0-alpha.3
  google_maps_flutter: ^2.2.2
  upgrader: ^11.3.1
  # in_app_update: ^4.0.1
  # phone_number: ^2.1.0
  sms_autofill: ^2.2.0
  auto_size_text: ^3.0.0
  json_annotation: ^4.8.0
  font_awesome_flutter: ^10.4.0
  flutter_branch_sdk: ^8.3.2
  go_router: ^14.7.1
  qr_flutter: ^4.0.0
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  google_maps: ^8.1.1
  cached_network_image: ^3.3.1
  lottie: ^3.0.0
  geocoding: ^3.0.0
  local_auth: ^2.1.7
  pinput: ^5.0.1
  video_player: ^2.8.6
  chewie: ^1.7.5
  flutter_rating_bar: ^4.0.1
  dartz: ^0.10.1
  # local_auth_ios: ^1.1.4
  local_auth_android: ^1.0.34
  share_plus: ^10.1.4
  clipboard: ^0.1.3
  package_info_plus: ^8.1.3
  geolocator: ^13.0.2
  connectivity_plus: ^6.1.2
  # google_maps_webservice: ^0.0.20-nullsafety.5
  permission_handler: ^11.0.1
  horizontal_data_table: ^4.3.1
  auto_size_text_field: ^2.2.4
  # rate_my_app: ^2.0.0
  intl: ^0.20.2
  local_auth_darwin: ^1.4.3
  device_info_plus: ^11.2.1
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  mobile_scanner: ^6.0.6
  flutter_google_maps_webservices: ^1.1.1
  # ai_barcode_scanner: ^6.0.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.1.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter_icons:
  image_path: "assets/images/touristsaver-app-logo..png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/google_sans_bold.ttf
        - asset: assets/fonts/google_sans_light.ttf
        - asset: assets/fonts/google_sans_medium.ttf
        - asset: assets/fonts/google_sans_regular.ttf
        - asset: assets/fonts/google_sans_thin.ttf
